export enum AuditResourceType {
  USER = 'USER',
  VOTER = 'VOTER',
  CANDIDATE = 'CANDIDATE',
  VOTE = 'VOTE',
  TOKEN = 'TOKEN',
  ELECTION = 'ELECTION',
  ELECTION_CONFIG = 'ELECTION_CONFIG',
  RESULTS = 'RESULTS',
  EXPORT = 'EXPORT',
  SECURITY = 'SECURITY',
  EMAIL = 'EMAIL',
}
