export enum AuditAction {
  // Authentication
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  ADMIN_LOGOUT = 'ADMIN_LOGOUT',

  // Voter Authentication
  VOTER_LOGIN_SUCCESS = 'VOTER_LOGIN_SUCCESS',
  VOTER_LOGIN_FAILED = 'VOTER_LOGIN_FAILED',
  VOTER_TOKEN_VERIFIED = 'VOTER_TOKEN_VERIFIED',
  VOTER_TOKEN_FAILED = 'VOTER_TOKEN_FAILED',

  // Voter Management
  VOTER_CREATED = 'VOTER_CREATED',
  VOTER_UPDATED = 'VOTER_UPDATED',
  VOTER_DELETED = 'VOTER_DELETED',
  VOTER_RESTORED = 'VOTER_RESTORED',
  VOTER_BULK_IMPORTED = 'VOTER_BULK_IMPORTED',

  // Candidate Management
  CANDIDATE_CREATED = 'CANDIDATE_CREATED',
  CANDIDATE_UPDATED = 'CANDIDATE_UPDATED',
  CANDIDATE_DELETED = 'CANDIDATE_DELETED',

  // Token/OTP Management
  TOKEN_GENERATED = 'TOKEN_GENERATED',
  TOKEN_SENT = 'TOKEN_SENT',
  TOKEN_RESENT = 'TOKEN_RESENT',
  TOKEN_VERIFIED = 'TOKEN_VERIFIED',
  TOKEN_FAILED = 'TOKEN_FAILED',

  // Voting
  VOTE_CAST = 'VOTE_CAST',

  // Election Management
  ELECTION_SCHEDULED = 'ELECTION_SCHEDULED',
  ELECTION_EXTENDED = 'ELECTION_EXTENDED',
  ELECTION_STATUS_CHANGED = 'ELECTION_STATUS_CHANGED',

  // Results
  RESULTS_VERIFIED = 'RESULTS_VERIFIED',
  RESULTS_PUBLISHED = 'RESULTS_PUBLISHED',
  PUBLIC_RESULTS_VIEWED = 'PUBLIC_RESULTS_VIEWED',

  // Export
  EXPORT_NON_VOTERS = 'EXPORT_NON_VOTERS',

  // Security
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  CSRF_VALIDATION_FAILED = 'CSRF_VALIDATION_FAILED',
  IP_EXTRACTED = 'IP_EXTRACTED',
  SECURITY_EVENT = 'SECURITY_EVENT',

  // Email
  EMAIL_SENT = 'EMAIL_SENT',
  EMAIL_FAILED = 'EMAIL_FAILED',

  // Token Batch Operations
  TOKEN_BATCH_GENERATED = 'TOKEN_BATCH_GENERATED',
  TOKEN_EMAIL_BATCH_SENT = 'TOKEN_EMAIL_BATCH_SENT',
  TOKEN_STALE_INVALIDATED = 'TOKEN_STALE_INVALIDATED',
  TOKEN_ELECTION_ACTIVATED_BATCH = 'TOKEN_ELECTION_ACTIVATED_BATCH',
  TOKEN_VOTER_CREATED_DURING_ELECTION = 'TOKEN_VOTER_CREATED_DURING_ELECTION',

  // Admin Dashboard
  DASHBOARD_STATS_VIEWED = 'DASHBOARD_STATS_VIEWED',
  VOTER_MONITOR_ACCESSED = 'VOTER_MONITOR_ACCESSED',
}
